enum EnumPopUp {
  REMOVER_DOCENTES,
  REMOVER_CURSOS,
  DOCENTE,
  DISCIPLINA,
  DISCIPLINAS,
  CURSO,
  GERANDO_PDF,
  ALTERAR_COMPETENCIAS,
  CONFIRMAR_CANCELAMENTO_DE_ATRIBUICAO_DE_COMPETENCIAS,
}

export default EnumPopUp;
